image: node:latest



cache:
  paths:
    - node_modules/



stages:
  - lint
  - test



testing-linting: 
  stage: lint
  script: 
    - npm install eslint eslint-config-airbnb eslint-config-standard eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-n eslint-plugin-promise eslint-plugin-react eslint-plugin-react-hooks
    - node_modules/eslint/bin/eslint.js .



integration-test:
  stage: test
  script: 
    - npm install
    - npm run test:cov
 


